<a href="https://colab.research.google.com/github/IlTACK-OH/MLguide_practice/blob/main/Untitled24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 ndarray 개요
넘파이의 기반 데이터 타입은 ndarray이다. ndarray를 이용하여 넘파이에서 다차원 배열을 쉽게 생걱하고 다양한 연산을 수행할 수 있다.

In [1]:
import numpy as np

In [4]:
# 1차원 데이터
array1 = np.array([1,2,3])
print('array1 type:',type(array1)) # data type 확인
print('array1 array 형태:',array1.shape) # 배열의 차원 확인

# 2차원 데이터
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:', array2.shape)

# 2차원 데이터
array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


# ndarray의 데이터 타입
ndarray내의 데이터값은 숫자 값, 문자열 값, 불 값 등이 모두 가능하다. 숫자형의 경우 int형, unsigned int형, float형,<br> 그리고 이보다 더 큰 숫자 값이나 정밀도를 위해 complex타입도 제공한다.<br> ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다.

In [7]:
list1 = [1,2,3]
print(type(list1))
array1= np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 **데이터 크기**가 더 큰 데이터 타입으로 형 변환을 일괄적용한다. 

In [8]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


ndarray 내 데이터 값의 타입 변경도 astype() 메서드를 이용해 할 수 있다. astype()에 인자로 원하는 타입을 문자열로 지정하면 된다.<br> 이렇게 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데, 메모리를 더 절약해야 할 때 보통 이용된다.<br>가령 int형으로 충분한 경우인데, 데이터 타입이 float라면 int형으로 바꿔서 메모리를 절약할 수 있다.<br>

메모리를 절약해봐야 얼마나 할 수 있는지 의구심이 들 수 있지만, 파이썬 기반의 머신러닝 알고리즘은 대부분 메모리로 데이터를 전체 로딩한 다음 이를 기반으로 알고리즘을 적용하기 때문에 대용량의 데이터를 로딩할 때는 수행속도가 느려지거나 메모리 부족으로 오류가 발생할 수 있다. 

In [9]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange,zeros,ones

In [10]:
# arange
squence_array = np.arange(10)
print(squence_array)
print(squence_array.dtype,squence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [11]:
# zeros
zero_array = np.zeros((3,2),dtype='int32') # dtype을 지정해주지 않으면 defalut로 float64혀의 데이터로 ndarray를 채운다.
print(zero_array)
print(zero_array.dtype,zero_array.shape)

#ones
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()
reshape()메서드는 ndarray를 특정 차원 및 크기로 변환한다.

In [12]:
array1= np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


지~~극히 당연한 얘기지만, reshape()는 지정된 사이즈로 변경이 불가능하면 오류를 발생시킨다.

In [13]:
array1.reshape(4,3)

ValueError: ignored

reshape를 효율적으로 사용하는 경우는 아마도 인자로 -1을 적용하는 경우일 것이다. -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해 준다. 

In [16]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


만일 위에서 살펴보았듯이 변경할 수 없는 shape을 입력하면 error를 발생한다.

In [17]:
array1 = np.arrange(10)
array4 = array1.reshape(-1,4)

AttributeError: ignored

`-1`인자는 `reshape(-1,1)`와 같은 형태로 자주 사용된다. `reshape(-1,1)`은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다. 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용된다. 

In [20]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist()) # tolist()는 ndarry를 list자료형으러 변환한다.
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
